modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
loggFile="logo.png"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="libx"
    mandatory=true
    versionRange="[1.20.1-5.0.12,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="botania"
    mandatory=true
    versionRange="[1.20.1-446,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="botanicalmachinery"
    mandatory=true
    versionRange="[1.20.1-3.0.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ae2"
    mandatory=true
    versionRange="[15.2.13,)"
    ordering="NONE"
    side="BOTH"