modLoader="javafml"
loaderVersion="[40,)"
license="Apache-2.0 license"
loggFile="logo.png"

[[mods]]
modId="botanicalextramachinery"
version="1.0.0"
displayName="Botanical Extra Machinery"
authors="LMor, nexxx_7"
description='''New and improved machines from the Botanical Machinery mod. Also new sparks and a mechanical orechid.'''

[[dependencies.botanicalextramachinery]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.botanicalextramachinery]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.botanicalextramachinery]]
    modId="libx"
    mandatory=true
    versionRange="[1.18.2-3.2.18,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.botanicalextramachinery]]
    modId="botania"
    mandatory=true
    versionRange="[1.18.2-435,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.botanicalextramachinery]]
    modId="botanicalmachinery"
    mandatory=true
    versionRange="[1.18.2-1.0.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.botanicalextramachinery]]
    modId="ae2"
    mandatory=true
    versionRange="[11.7.6,)"
    ordering="NONE"
    side="BOTH"